### ISSUE TITLE
Bot plays only 2 minutes of MP3 track - transcoding issue

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/djSonic#35]
Hint from @kpostekk: overflow of `/dev/shm` - Linux shared memory; by default its' size is limited to 64MB on Docker.

- [x] resize `/dev/shm` by utilizing `shm_size`

**Comment by kpostekk** [comment]
in docker-compose
```docker-compose
services:
  bot:
    volumes:
      - type: tmpfs
        source: shm_bot
        target: /dev/shm
```

**Comment by rafalopilowski1** [comment]
Seems to be fixed. Closing.
Thanks @kpostekk :)
